# version: '3.3'
# volumes:
#   data:
# services:
#   db:
#     image: arm64v8/mysql
#     ports:
#       - "3306:3306"
#     volumes:
#       - data:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_DATABASE=app_development
#   app:
#     image: phpmyadmin/phpmyadmin:latest
#     links:
#       - db
#     ports:
#       - 80:80
#     environment:
#       - PMA_ARBITRARY=1
version: '3.3'
services:
  postgres:
    image: postgres
    volumes:
      - ./pgsql-tables.sql:/docker-entrypoint-initdb.d/01-pgsql-tables.sql
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"